### ISSUE TITLE
One line of code implementation change

### ISSUE THREAD

**Issue by nicholasnge** [KU-CVLAB/RAIN-GS#11]
Hello, thanks for your work!

The paper mentions both changes can be implemented each with one line of code. 
I am not familiar with the entire code of 3DGS, could I please know which line(s) I should look at to understand your changes?

**Comment by crepejung00** [comment]
Hi, thank you for your interest in our work!

An explanation of our one line of code implementation is mentioned in a previous issue.
We kindly guide your attention to issue #7.

Thanks.
