### ISSUE TITLE
about build

### ISSUE THREAD

**Issue by Seektruth321** [KU-CVLAB/RAIN-GS#18]
Hi, the cu117 I'm using reports an error installing the submodules，
![image](https://github.com/user-attachments/assets/df97eae3-358f-44ae-bc88-dd07c3bf7faf)

When I use the original 3dgs method of installing the submodule it succeeds but the training reports an error
![image](https://github.com/user-attachments/assets/d5b0b26d-d655-44e7-9934-57b7677c1a37)

Show that -s or -source_path is not recognised.
![image](https://github.com/user-attachments/assets/2e381407-d4c0-4d34-9b55-8f59a02c1d5e)
Why is that, please?

**Comment by StarsTesla** [comment]
@2693748650 Hi, did you solve this error, could you share it out, it seems the submodule cannot directly build
