### ISSUE TITLE
--ours has RuntimeError

### ISSUE THREAD

**Issue by gmcarmen** [KU-CVLAB/RAIN-GS#2]
I encountered the following RuntimeError when training with --ours, but there is no problem with --DSV，How to solve it 
![RAbug](https://github.com/KU-CVLAB/RAIN-GS/assets/163381818/ed7a329c-7cf8-43f5-a3b1-7fea1bc83766)

**Comment by crepejung00** [comment]
Hi, thank you for your interest in our work !

Could you explain what kind of dataset you are trying to train on? 
We currently tested on Mip-NeRF360, TNT, and Deep Blender datasets which were all fine.

Thanks!

**Comment by gmcarmen** [comment]
I tested with my own data, using colmap processed the data. the dat like this:
![kele_example](https://github.com/KU-CVLAB/RAIN-GS/assets/163381818/080b7de1-4783-4e05-8141-ea131cd8f937)

**Comment by crepejung00** [comment]
Hmm quite not sure what is causing the problem.
Can you share your data with us? We will check it as soon as possible.
If the data is confidential, you can send an email to me right away. 
jaewoojung00@korea.ac.kr

Thanks.

**Comment by gmcarmen** [comment]
It might be an issue with my data. When I switched to a different dataset, it worked. Thank you for your response.

**Comment by crepejung00** [comment]
Good to hear that!
I will now close this issue.
If any additional error occurs open it again anytime.

Thanks!!
