### ISSUE TITLE
error: option -s not recognized

### ISSUE THREAD

**Issue by alexzhenglong** [KU-CVLAB/RAIN-GS#4]
thanks for great works ,but i do have some questions,
(3dg) alex@alex-System-Product-Name:~/RAIN-GS-main$ python train.py -s data/truck  --eval --ours
usage: train.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: train.py --help [cmd1 cmd2 ...]
   or: train.py --help-commands
   or: train.py cmd --help
thanks a lot

**Comment by crepejung00** [comment]
Hi, thanks for the interest in our work!

Could you please provide a more detailed screenshot of the error?

Thanks!

**Comment by alexzhenglong** [comment]
thanks for your reply,here is it
![2024-03-17 11-44-43屏幕截图](https://github.com/KU-CVLAB/RAIN-GS/assets/143620775/d2a72652-8eb9-436e-998d-b35ac7bb0eaa)

**Comment by crepejung00** [comment]
Can you share what version of python and cuda you are working on?

We just tested our code after re-cloning this repo and it actually worked fine. Could you please try --source_path instead of -s? 

Thanks.

**Comment by alexzhenglong** [comment]
i guess maybe my version of cuda goes wrong,it is just 11.8 with python 3.8,i will try to rebuild my env,thanks so much!
