### ISSUE TITLE
Slv and low pass code location 

### ISSUE THREAD

**Issue by ishaybee** [KU-CVLAB/RAIN-GS#7]
Hi
In the paper you are saying that it is a 1 line modification for your method.
Can you point out where are the location of these modifications?

**Comment by renhaofan** [comment]
@ishaybee
https://github.com/KU-CVLAB/RAIN-GS/blob/4f72d61788347fe09da5edb395d8ab080aabae5e/submodules/diff_gaussian_rasterization/cuda_rasterizer/forward.cu#L99

**Comment by crepejung00** [comment]
Hi, sorry for the late reply.

1. Sparse-large-variance (SLV) random initialization can be implemented by just changing the initial number of Gaussians!
The change is implemented in line 160 implicitly.

https://github.com/KU-CVLAB/RAIN-GS/blob/4f72d61788347fe09da5edb395d8ab080aabae5e/scene/dataset_readers.py#L159-L181

2. The progressive Gaussian low-pass filter control can be found here:
line 91~97 is a simple definition of the low-pass filter value which is written in multiple lines for readability.
This low-pass value is then added to the covariance as @renhaofan mentioned.

https://github.com/KU-CVLAB/RAIN-GS/blob/4f72d61788347fe09da5edb395d8ab080aabae5e/train.py#L90-L102

Thanks!
