### ISSUE TITLE
Toy Experiment

### ISSUE THREAD

**Issue by AdityaDhaulakhandi** [KU-CVLAB/RAIN-GS#9]
Can you provide code for the toy experiment (1D Gaussian)? I want to understand the workings of the Gaussian splatting model at a deeper level.

Thanks,
Aditya.

**Comment by crepejung00** [comment]
Hi, sorry for the late reply.

We are currently a bit busy with our next work but will try to provide the codes for our toy experiment as soon as possible. In the meantime, we think that this implementation is not very complex, so you can try to implement it yourself!

The toy experiment is just a simple 1D regression task learned with multiple 1D Gaussians which will act similar to a Gaussian Mixture Model. The implementation can be easily done by utilizing the normal library of either numpy or pytorch! 
We have provided a detailed explanation of how we implemented our toy experiment in Section C of the Appendix of our paper.

Thank you for your interest in our work!
I will just close the issue for now.
